name: Versionamento Automático HTML/CSS

on:
  push:
    branches:
      - main   

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: phips28/gh-action-bump-version@v10
        with:
          tag-prefix: "v"           # tags ficarão v1.0.0, v1.0.1 etc.
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
